# Generated by Django 3.2.11 on 2024-08-17 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_favoritebook'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='genres',
            field=models.CharField(default='fiction', max_length=50),
        ),
        migrations.AddField(
            model_name='book',
            name='recap',
            field=models.CharField(blank=True, default='', max_length=500, null=True),
        ),
    ]
